# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  FLUTTER_VERSION: 3.38.4

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

  test:
    runs-on: ${{ matrix.runner }}
    env:
      GITHUB_TOKEN: ${{ secrets.token }}
    strategy:
      matrix:
        runner:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  e2e-test:
    name: End-to-End Tests (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    env:
      GITHUB_TOKEN: ${{ secrets.PUBLIC_ONLY_PAT }}
    strategy:
      matrix:
        runner:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get

      - name: Activate flutterpi_tool globally
        run: flutter pub global activate -spath .

      - name: Run e2e tests
        run: dart test e2e
